server:
  port: 8080

spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: jai
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: AF53F42815FDDA3E194338615F531ALSDJFODFSJDF897SF9S7F09AF09SAF79F7S09DF87AS09FSD0F976SDAF09DS7AF6SD097F6SD08F76SDF097DS6F0ADS7F6DSA0F7AS6DF087SDF60SD8F76DS0F87DS6F0SD87F6SD08F7S6DF08S7D6F0ADS87F6SD0F87ADS6F08SDA7F6DS0F76DS0F87DSF05SDF84SDFAD4S
  expiration: 10000000000000

logging:
  level:
    org:
      springframework:
        security: DEBUG